### ISSUE TITLE
npm snapshot process does not end

### ISSUE THREAD

**Issue by mygrexit** [wictorwilen/ring-timelapse#10]
Hey, I would like to take snapshots every minute, but for some reason the snapshot sometimes takes up to 10 minutes to finish even though the file/photo has already been created.

When the next snapshot starts I then get the following error message:

`crond: user root: process already running: cd /app && npm run snapshot`

For me it works by adding a timeout like this: 

`cd /app && timeout 30s npm run snapshot`

But of course, that's more of a dirty hack.

**Comment by wictorwilen** [comment]
Please use the updated version (2.0.0)
