### ISSUE TITLE
Error since 17:30 - 27/7/2021

### ISSUE THREAD

**Issue by CURRTIS1** [wictorwilen/ring-timelapse#2]
Error below, created a new token to try and still the same.
Output from the docker logs:

crond: USER root pid 167 cmd run-parts /etc/periodic/15min

crond: USER root pid 168 cmd cd /app && npm run snapshot

(node:179) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)
    at Request.<anonymous> (/app/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:179) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:179) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by CURRTIS1** [comment]
Noticed ring won't be supporting email 2fa so changed the token to one gathered using ssm 2fa however it still fails.
Also noticed within my ring application the authorized devices list goes up to 27th July:
https://account.ring.com/account/control-center/authorized-devices
After changing to SSM 2fa I see no further authorized devices using the ring-api.

**Comment by wictorwilen** [comment]
Thanks for reporting. I'll look into this!

**Comment by wictorwilen** [comment]
@CURRTIS1 - can you please get the latest docker image now and test it. There was a reported issue with the Ring API that has been fixed and I've updated the dependency

**Comment by CURRTIS1** [comment]
@wictorwilen pulled the latest image and it now works, thank you for looking in to this!
