### ISSUE TITLE
ring-client-api multiple connection in control center

### ISSUE THREAD

**Issue by ghost** [wictorwilen/ring-timelapse#5]
Hi,

Just check my control-center and in the authorized devices I have a lot of ring-client-api "devices".
![image](https://user-images.githubusercontent.com/89838505/131975563-be10b00d-4743-4e0d-b09a-a79729d74a81.png)

I'm running the last docker image. I already tried to stop it and relaunch with another token but it's not working either.

Thank your for your help ;)

**Comment by developedsoftware** [comment]
Got the same ! 
![Uploading 20C5B703-1E27-4DC6-A30E-8345FBFE709F.png…]()
